configfile: "../config.yaml"
workdir: "../TempFiles/"

rule all:
    input:
        expand("sorted_read/{sample}.bam.bai", sample = config['TestSamples'])

rule bam_sort:
    input:
        "../Data/{sample}.bam"
    output:
        "sorted_read/{sample}.bam"
    threads: config["Threads"]
    log: "log/bamsort/{sample}.log"
    shell:
        "samtools sort {input} > {output} --threads {threads} 2> {log}"

rule index_bam:
    input:
        "sorted_read/{sample}.bam"
    output:
        "sorted_read/{sample}.bam.bai"
    threads: config["Threads"]
    log: "log/bamsort/{sample}.bai.log"
    shell:
        "samtools index {input} 2> {log}"

# need to get and convert human and mouse genome for the following rules. But Disc Quota.
rule variant_calling:
    input:
        ref="data/mm10.fa",
        fai="data/mm10.fa.fai",
        bam="sorted_read/{sample}.bam"
    output:
        "{sample}.vcf"
    message:
        "Performing Variant Calling with freebayes for the following bam files: {input.bam}"
    threads: config["Threads"]
    log: "log/variant_calling/{sample}.log"
    shell:
        "freebayes-parallel <(fasta_generate_regions.py {input.fai} 100000) {threads} -f {input.ref} -b {input.bam} > {output} 2> {log}"

rule clean:
    shell:
        "rm -f -r sorted_read/ log/"
